# golangci-lint configuration for slb
# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - gofmt
    - goimports
  disable:
    # Disable unused linter - too many false positives in development
    - unused

linters-settings:
  errcheck:
    # Don't check error returns in defer statements in test files
    check-type-assertions: false
    check-blank: false
    # Exclude common patterns that are safe to ignore
    exclude-functions:
      # In test code, these are often cleanup operations where failure doesn't matter
      - (io.Closer).Close
      - (*os.File).Close
      - (*database/sql.Tx).Rollback
      - (*database/sql.DB).Close
      - (net.Conn).Close
      - (*net.Conn).SetReadDeadline
      - os.Chmod
      - io.Copy
      - (*bytes.Buffer).Write
      - (net.Conn).Write
      - os.MkdirAll
      - json.Unmarshal
      - (*bytes.Buffer).ReadFrom

issues:
  # Exclude some issues in test files
  exclude-rules:
    # Allow unchecked error returns in test cleanup (defer statements)
    - path: _test\.go
      linters:
        - errcheck

    # Ignore ineffassign for intentional reassignments
    - linters:
        - ineffassign
      text: "ineffectual assignment"

    # Ignore gosimple suggestions in existing code
    - linters:
        - gosimple
      text: "S1008|S1017|S1030|S1039"

    # Ignore deprecated API warnings - these are backwards compatibility concerns
    - linters:
        - staticcheck
      text: "SA1019"

    # Ignore nil context in tests
    - path: _test\.go
      linters:
        - staticcheck
      text: "SA1012"

    # Ignore empty branch checks - these are often intentional patterns
    - linters:
        - staticcheck
      text: "SA9003"

    # Ignore unused value warnings in development code
    - linters:
        - staticcheck
      text: "SA4006"

    # Ignore possible nil pointer dereference in test helpers
    - linters:
        - staticcheck
      text: "SA5011"
